- docs/AboutUs.md
- docs/DeveloperGuide.md
- docs/UserGuide.md
- docs/index.md
- docs/team/estellelim.md
- docs/team/evan.md
- docs/team/kohkakohla.md
- docs/team/mingyang.md
- docs/team/plishh.md
Update README page by changing all instances of AB-3 to VolunTier.
> Update README page

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/person/Hours.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
- src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
- src/test/java/seedu/address/testutil/PersonUtil.java
> Added the add command

- docs/DeveloperGuide.md
Refined
- user story
- use cases
- glossary
Closes #39
> Refine Developer Guide

- src/main/java/seedu/address/logic/LogicManager.java
> Fix not saving to storage bug

- src/main/resources/view/MainWindow.css
- src/main/resources/view/PersonListPanel.css
> Fix Ui PersonCard

- docs/DeveloperGuide.md
- docs/diagrams/UndoSequenceDiagram-Logic.puml
- docs/diagrams/ViewSequenceDiagram.puml
- src/main/java/seedu/address/logic/commands/ViewCommand.java
- src/main/java/seedu/address/logic/commands/ViewTuteeChartCommand.java
- src/test/java/seedu/address/logic/commands/ViewCommandTest.java
- src/test/java/seedu/address/logic/commands/ViewTuteeChartCommandTest.java
fixes #77 
fixes #79 
Add UML diagram for View Command
> Branch add uml

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/AddTuteeCommand.java
- src/main/java/seedu/address/logic/commands/AddTutorCommand.java
- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/HistoryCommand.java
- src/main/java/seedu/address/logic/commands/ViewCommand.java
> Change formatting of success messages

- src/main/java/seedu/address/logic/commands/ImportCommand.java
- src/main/java/seedu/address/storage/CsvImport.java
- src/test/data/CsvImportTest/duplicatePersonsCsv.csv
- src/test/data/CsvImportTest/extraHeadersCsv.csv
- src/test/data/CsvImportTest/extraRowsCsv.csv
- src/test/data/CsvImportTest/failedPersonsCsv.csv
- src/test/data/CsvImportTest/missingHeadersCsv.csv
- src/test/data/CsvImportTest/missingRowsCsv.csv
- src/test/data/CsvImportTest/typicalPersonsCsv.csv
- src/test/java/seedu/address/logic/commands/ImportCommandTest.java
- src/test/java/seedu/address/storage/CsvImportTest.java
- src/test/java/seedu/address/testutil/CsvImportUtil.java
> Add tests for CsvImport and ImportCommand

- src/main/java/seedu/address/logic/commands/FindSubjectCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/FindSubjectCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/person/PersonHaveSubjectPredicate.java
- src/main/java/seedu/address/ui/CommandBox.java
- src/main/java/seedu/address/ui/MainWindow.java
> Implement findSubject

- src/main/java/seedu/address/model/person/Name.java
> Make name parsing more robust

- src/main/java/seedu/address/logic/commands/ViewTutorChartCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/ViewCommandParser.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/ui/ChartWindow.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/test/java/seedu/address/logic/commands/AddLessonCommandTest.java
- src/test/java/seedu/address/logic/commands/CommandResultTest.java
- src/test/java/seedu/address/logic/commands/ViewTuteeChartCommandTest.java
- src/test/java/seedu/address/logic/commands/ViewTutorChartCommandTest.java
- src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
- src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
- src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
- src/test/java/seedu/address/storage/StorageManagerTest.java
fixes #95 
1. Added test cases for some files
2. Changed ViewTuteeChartCommand to ViewTutorChartCommand as viewing the hours for tutor is more useful.
> Branch updates v1.4

- docs/diagrams/ModelClassDiagram.puml
> Add UML for ModelClassDiagram.puml

- src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
- src/test/java/seedu/address/logic/commands/AddLessonCommandTest.java
- src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
- src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
- src/test/java/seedu/address/storage/StorageManagerTest.java
> Addlesson tests

- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/ui/PersonCard.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/MainWindow.css
- src/main/resources/view/PersonListCard.css
- src/main/resources/view/PersonListCard.fxml
> Add Subject to personCard

- src/main/java/seedu/address/logic/commands/ImportCommand.java
- src/main/java/seedu/address/storage/CsvImport.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/test/data/CsvImportTest/duplicatePersonsCsv.csv
- src/test/data/CsvImportTest/extraHeadersCsv.csv
- src/test/data/CsvImportTest/extraRowsCsv.csv
- src/test/data/CsvImportTest/failedPersonsCsv.csv
- src/test/data/CsvImportTest/missingHeadersCsv.csv
- src/test/data/CsvImportTest/missingRowsCsv.csv
- src/test/data/CsvImportTest/typicalPersonsCsv.csv
- src/test/java/seedu/address/logic/commands/ImportCommandTest.java
Fixes #116, #117 
- Fixed CsvImport to work with subjects and the relevant tests that are affected
- Adjusted the message returned by ImportCommand to accurately reflect rows that have data that failed certain constraints
> Fix CsvImport tests

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/storage/JsonAdaptedSubjectConverter.java
- src/main/resources/view/PersonListCard.fxml
- src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
- src/test/java/seedu/address/logic/parser/AddTutorCommandParserTest.java
> Fix import bug

- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/main/java/seedu/address/storage/JsonAdaptedTutee.java
- src/main/java/seedu/address/storage/JsonAdaptedTutor.java
- src/test/java/seedu/address/storage/JsonAdaptedTuteeTest.java
- src/test/java/seedu/address/storage/JsonAdaptedTutorTest.java
> Fix bug where JSON data would not initialise properly

- src/main/java/seedu/address/ui/HelpWindow.java
- src/main/resources/view/HelpWindow.css
- src/main/resources/view/HelpWindow.fxml
> Refine Help Window

- src/main/java/seedu/address/logic/commands/AddTuteeCommand.java
- src/main/java/seedu/address/logic/commands/AddTutorCommand.java
- src/main/java/seedu/address/model/person/Name.java
> Fix name constraints

- src/main/java/seedu/address/model/person/Hours.java
> Fix hours and vtc bug

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/ImportCommand.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/lesson/UniqueLessonList.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/storage/CsvImport.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/main/java/seedu/address/storage/JsonAdaptedTutor.java
- src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
- src/test/data/CsvImportTest/duplicatePersonsCsv.csv
- src/test/data/CsvImportTest/extraHeadersCsv.csv
- src/test/data/CsvImportTest/extraRowsCsv.csv
- src/test/data/CsvImportTest/failedPersonsCsv.csv
- src/test/data/CsvImportTest/missingHeadersCsv.csv
- src/test/data/CsvImportTest/missingRowsCsv.csv
- src/test/data/CsvImportTest/typicalPersonsCsv.csv
- src/test/java/seedu/address/logic/commands/AddTuteeCommandTest.java
- src/test/java/seedu/address/logic/commands/AddTutorCommandTest.java
- src/test/java/seedu/address/logic/commands/ImportCommandTest.java
- src/test/java/seedu/address/logic/parser/ImportCommandParserTest.java
Fix lesson disappearing on edit person bug and csvImport having wrong indexing bug.
> Fix lesson and csvImport bug

- docs/UserGuide.md
- src/main/java/seedu/address/logic/parser/FindSubjectCommandParser.java
- src/main/java/seedu/address/model/person/Address.java
> Fix findSubject with multiple arguments

- docs/UserGuide.md
- src/main/java/seedu/address/logic/commands/ViewCommand.java
- src/main/java/seedu/address/model/person/Name.java
- src/main/java/seedu/address/model/person/Phone.java
fixes #262 
fixes #273 
fixes #264
> Fix user guide
